### ISSUE TITLE
Bad indentation in switch-case statement - no statement-case-intro syntactic element symbol

### ISSUE THREAD

**Issue by exu** [emacs-php/php-mode#111]
C mode properly detect statement-case-intro syntactic element symbol

```
void spam( enum Ingredient i )
{
    switch( i ) {
    case Ham:
        [*]be_a_pig();
        break;
    case Salt:
        drink_some_water();
        break;
    default:
        {
            what_is_it();
            break;
        }
    }
}

[*] - statement-case-intro in C
```

http://www.gnu.org/software/emacs/manual/html_node/ccmode/Switch-Statement-Symbols.html#Switch-Statement-Symbols

In PHP mode there is no such statement:

```
                switch ($type) {
                    case 'order':
                    [*]$clients_wants_order = $row['customer_wants_order'];
                    break;
                    case 'preorder':
                    $clients_wants_preorder = $row['customer_wants_preorder'];
                    break;
                }

[*] - brace list entry
```

You can `C-c C-o` under cursor to detect what is current syntactic element symbol.

It would be great if PHP mode correctly set this, currently with my previous pull request Symfony2 code style have bad indentation.

**Comment by zonuexe** [comment]
I'm closing it now because it looks like there is no problem
