### ISSUE TITLE
Wrong indentation

### ISSUE THREAD

**Issue by crocket** [emacs-php/php-mode#138]
```
preg_replace_callback('/=\?[^\s?]+\?[^\s?]\?[^\s?]+\?=/',
function ($match) {
    $ret=imap_utf8($match[0]);
    if($ret === $match[0])
        $ret=mb_decode_mimeheader($match[0]);
    return $ret;
}, $header);
```

If you press TAB in an anonymous function, indentation goes wrong.

**Comment by sten0** [comment]
I think [Debian Bug #286416](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=286416) might be related to this issue, and maybe helps clarify the nature of the problem.

Cyril Bouthors writes:

> I think php-elisp makes wrong indentation of the switch/case
> statements when switch() is used inside any curly braces like for() or
> function().
> 
> First example, switch is aligned on the first column, php-elisp makes
> a correct indentation:
> 
> switch ($country) {
>  case 'France':
>    $phone_prefix=33;
>    break;
> }
> 
> Second example, switch is used inside a function() and is not aligned
> on the first column, php-elisp makes an _incorrect_ indentation:
> 
> function foo()
> {
>   switch ($country) {
>   case 'France':
>     $phone_prefix=33;
>     break;
>   }
> }
> 
> The second example should be indented as:
> 
> function foo()
> {
>   switch ($country) {
>     case 'France':
>       $phone_prefix=33;
>       break;
>   }
> }
>

**Comment by sten0** [comment]
Ah, quoting dropped the critical indentation.  Oops.  Here's what that bug actually reported:
```
First example, switch is aligned on the first column, php-elisp makes
a correct indentation:

switch ($country) {
 case 'France':
   $phone_prefix=33;
   break;
}


Second example, switch is used inside a function() and is not aligned
on the first column, php-elisp makes an _incorrect_ indentation:

function foo()
{
  switch ($country) {
  case 'France':
    $phone_prefix=33;
    break;
  }
}

The second example should be indented as:

function foo()
{
  switch ($country) {
    case 'France':
      $phone_prefix=33;
      break;
  }
}
```
I can confirm that the "incorrect indentation" is present in php-mode-1.21.4.

**Comment by mallt** [comment]
@sten0 If you change the php-style to `drupal` you should be able to achieve the desired indendation: <kbd>M-x php-set-style</kbd> and then select `drupal`.

**Comment by sten0** [comment]
Thank you @mallt :-D

**Comment by sten0** [comment]
Tijs Mallaerts <notifications@github.com> writes:

> @sten0 If you change the php-style to `drupal` you should be able to achieve the desired indendation: <kbd>M-x php-set-style</kbd> and then select `drupal`.
>

Thank you, I was able to close Debian bug with this info :-)
