### ISSUE TITLE
Recursive load when loading php-mode, manually byte compiled

### ISSUE THREAD

**Issue by ramnes** [emacs-php/php-mode#269]
Hi,

When I byte compile my `.emacs.d` and launch Emacs, I get the following error:

```
Warning (initialization): An error occurred while loading `/home/gg/.emacs.d/init.elc':

error: Recursive load, /home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc, /home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc, /home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc, /home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc, /home/gg/.emacs.d/site-lisp/php-mode/php-mode.\
elc, /home/gg/.emacs.d/lisp/init-requires.elc, /home/gg/.emacs.d/init.elc
```

With `emacs --debug-init`:

```
Debugger entered--Lisp error: (error "Recursive load" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.$
  signal(error ("Recursive load" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php-mode/php-mode.elc" "/home/gg/.emacs.d/site-lisp/php$
  byte-code("\303\304^H #\210\305^H!\210\306\n@\nA\"\207" [sym mode err message "Eval error in the `c-lang-defconst' for `%s' in %s:" makunbound signal] 4)
  c-get-lang-constant(c-mode-menu (cc-langs php-mode) php-mode)
  byte-code("\301\302^H\303\304\305\306\307\310#B$\207" [php-mode-map easy-menu-do-define php-mode-menu "PHP Mode Commands" "PHP" c-get-lang-constant c-mode-menu (cc-langs php-mode) php-mode] 9)
  require(php-mode)
  byte-code("\300\301!\210\300\302!\210\300\303!\210\300\304!\210\300\305!\210\300\306!\210\300\307!\210\300\310!\210\300\311!\210\300\312!\210\300\313!\210\300\314!\210\300\315!\210\300\316!\210\300\317!\210\300\320!\210\300\321!\210\300\322!\210\300\323!\210\300\324!\210$
  load("init-requires")
  byte-code("\306^X\307\310!\210\311 \210)\312\313\314\315!\"\210\316   \317\"^Q\320\321!\210\320\322!\210\320\323!\210\320\324!\210\320\325\326\"\2034^@\327\330\331\"\210\332^R\333\334\335\"\210\336\337\340\341\342$\210\343\337\326\"\210\312\344\314\345!\"\210\346^S\347 \$
  load("/home/gg/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\211#\210^K\322=\203a^@\324\325\326\307^H\327Q!\"\323^A\322\211#\210^K\322=\203`^@^A^S\$
  command-line()
  normal-top-level()
```

Removing php-mode from my requires makes Emacs starting without any error.

You can find my [emacs configuration here](https://github.com/ramnes/.emacs.d). `bin/compile` is what I use to compile my files (it's just launching my `compile.el` with Emacs).

Cheers!

**Comment by syohex** [comment]
Hmm, I cannot reproduce this issue. Which emacs version did you use ?

**Comment by ramnes** [comment]
I'm on master's HEAD.

**Comment by ramnes** [comment]
And I just tried against master HEAD (3371352), that doesn't change.

**Comment by ejmr** [comment]
What Emacs version info do you see if you press `C-h C-a`?  E.g. "GNU Emacs 25.0.50.16 (x86_64-unknown-linux-gnu, GTK+ Version 3.12.2)".

**Comment by ramnes** [comment]
GNU Emacs 24.5.1 (x86_64-pc-linux-gnu), compiled under Gentoo with the following USE flags enabled: `acl dbus xpm zlib`, and the following disabled: `-X -Xaw3d -alsa (-aqua) -athena -games -gconf -gfile -gif -gnutls -gpm -gsettings -gtk -gtk3 -gzip-el -hesiod -imagemagick -inotify -jpeg -kerberos -libxml2 -livecd -m17n-lib -motif -pax_kernel -png (-selinux) -sound -source -svg -tiff -toolkit-scroll-bars -wide-int -xft`.

**Comment by ejmr** [comment]
Thank you for the info.  Like @syohex I cannot reproduce the error, but I will try to mirror your setup as best I can to test it out.

**Comment by ramnes** [comment]
Thanks. For info, I just tried on an other machine where I don't have any USE flag enabled, and I still have the same error.

Compiling the `.el` files seems to works correctly:
```
Checking /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton...
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-classobj.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-classobj.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-control-structures.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-control-structures.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-crack.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-crack.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-dio.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-dio.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-dom.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-dom.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-exceptions.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-exceptions.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-exif.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-exif.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-ext.el...

In toplevel form:
site-lisp/php-mode/skeleton/php-ext.el:31:15:Warning: reference to free
    variable `php-ext-path'
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-ext.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-filesystem.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-filesystem.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-gd.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-gd.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-math.el...

In php-atanh:
site-lisp/php-mode/skeleton/php-math.el:79:18:Warning: function `php-atanh'
    defined multiple times in this file
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-math.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-pcre.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-pcre.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-regex.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-regex.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-simplexml.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-simplexml.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-strings.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-strings.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-var.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-var.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-xmlparser.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-xmlparser.elc
Compiling /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-xmlreader.el...
Wrote /home/ramnes/.emacs.d/site-lisp/php-mode/skeleton/php-xmlreader.elc
Checking /home/ramnes/.emacs.d/site-lisp/php-mode/tests...
Checking /home/ramnes/.emacs.d/site-lisp/popup-el/etc...
Checking /home/ramnes/.emacs.d/site-lisp/popup-el/tests...
Compiling /home/ramnes/.emacs.d/site-lisp/popup-el/tests/popup-interactive-test.el...
```

**Comment by ramnes** [comment]
I just made some `git bisect`, and the first commit to introduce that problem is  dce73c505f6bdc3847f612850066da1f26af4f24.

**Comment by ejmr** [comment]
Awesome, thank you for taking it upon yourself to do the bisection.  That helps a lot :smile:

**Comment by phracek** [comment]
I have added php-mode in Fedora distribution and during compilation I see:

~~~
Wrote /home/phracek/work/Fedora/emacs-php-mode/php-mode-1.17.0/skeleton/php-exif.elc

In toplevel form:
skeleton/php-ext.el:31:15:Warning: reference to free variable `php-ext-path'
Wrote /home/phracek/work/Fedora/emacs-php-mode/php-mode-1.17.0/skeleton/php-ext.elc
Wrote /home/phracek/work/Fedora/emacs-php-mode/php-mode-1.17.0/skeleton/php-filesystem.elc
Wrote /home/phracek/work/Fedora/emacs-php-mode/php-mode-1.17.0/skeleton/php-gd.elc

In php-atanh:
~~~

I use emacs-24.5 version.

If I open e.g. index.php which looks like:
<html>
<?php
   echo " I'm php script"
>
</html>

I see message "File mode specification error: (void-variable php-ext-path)"

How can I fix it?

**Comment by syohex** [comment]
@phracek Please load php-ext as below.(And your issue is not related to this issue.)

```
(eval-after-load 'php-mode
  '(require 'php-ext))
```

See
- https://github.com/ejmr/php-mode#installation

**Comment by mauser2** [comment]
when it occurred, it shows multiple defined of below from php-math.el:
(define-skeleton php-atanh
  "Insert an atan statement"
  ""
  > "atanh(" (skeleton-read "Number? ") ");" \n
)

remove the duplicated one, remove php-math.elc, issue then disappeared

**Comment by phil-s** [comment]
I just encountered this after starting Emacs and attempting to load my previous desktop file. I was getting the error both when loading php-mode (compiled or uncompiled), and also when trying to compile it. It looks like the same trigger. I ended up restarting Emacs without modifying php-mode.el, after which everything was again fine (and everything had previous been find with the same code). I use tarsius' auto-compile library, and I believe it had recompiled *something* when starting that first time, but I'm afraid I didn't check what that was before restarting again. I'm not sure whether this is helpful at all, but I just wanted to add another data point.

**Comment by larver-imvu** [comment]
FWIW I had a recursive load error using this config: https://github.com/listx/syscfg/commit/8a32777f010163c7d73f1f3add607259bfa7016d --- I got around it by deleting php-mode.elc from my `elpa` folder.

**Comment by artukrap** [comment]
Still active bug for me.

**Comment by tomchinery** [comment]
Just encountered this error as well running emacs 24 on Ubuntu. 

```
File mode specification error: (error "Recursive load" "/home/tom/.emacs.d/elpa/php-mode-20170201.1842/php-mode.elc" "/home/tom/.emac\
s.d/elpa/php-mode-20170201.1842/php-mode.elc" "/home/tom/.emacs.d/elpa/php-mode-20170201.1842/php-mode.elc" "/home/tom/.emacs.d/elpa/\
php-mode-20170201.1842/php-mode.elc" "/home/tom/.emacs.d/elpa/php-mode-20170201.1842/php-mode.elc")  
```

Any ideas?

**Comment by artukrap** [comment]
@tomchinery Deleting all related to PHP-mode helps, however only till next spacemacs restart, so for now, I just on VS Code for PHP and everything else on spacemacs.

**Comment by tomchinery** [comment]
@artukrap That sucks, I'll investigate further after work. Thanks.

**Comment by tomchinery** [comment]
Installing php-mode manually with the php-mode.el file is my workaround for now.

**Comment by PrestanceDesign** [comment]
Same problem here.
My configuration :

#### System Info :computer:
- OS: gnu/linux
- Emacs: 24.5.1
- Spacemacs: 0.200.7
- Spacemacs branch: master (rev. c2774bc)
- Graphic display: t
- Distribution: spacemacs
- Editing style: vim
- Completion: helm
- Layers:
```elisp
(javascript html php python helm auto-completion gtags chrome search-engine emacs-lisp git gnus markdown
            (org :variables org-enable-bootstrap-support t org-enable-github-support t org-enable-reveal-js-support t)
            (shell :variables shell-default-height 30 shell-default-position 'bottom)
            syntax-checking version-control)
```

**Comment by syohex** [comment]
I cannot reproduce. Please remove byte-compiled file(`*.elc`) and try again.

**Comment by PrestanceDesign** [comment]
I just did `find ~/.emacs.d/elpa/php* -name "*elc" -delete` and it's OK now, thx. :)
An idea what's happen ?

**Comment by ramnes** [comment]
@syohex @PrestanceDesign : the whole idea of this issue is that `php-mode` doesn't work *when byte-compiled*. So yeah, if you remove the `.elc` files, it does work.

Also, I just verified, and the issue is still present on the master branch head.

**Comment by syohex** [comment]
@ramnes Could you show us minimum configuration which reproduces this issue ? I cannot reproduce this issue yet.

**Comment by PrestanceDesign** [comment]
@ramnes OK, thx for the information !

**Comment by ramnes** [comment]
@syohex : there you go, I stripped my configuration from all the non-related stuff here : https://github.com/ramnes/.emacs.d/tree/issue/php-mode/269

Just clone it, `./compile` and `emacs`.

I guess the issue is related to the way things are loaded in my configuration, since I can't reproduce it with a simpler tree.

**Comment by syohex** [comment]
@ramnes This is your environment issue. Please rename compile.el to another name. 

1. compile.el loads init-requires.el
2. init-requires.el loads php-mode.el
3. php-mode.el loads flymake.el
4. flymake.el loads compile.el
5. compile.el loads init-requires.el infinite loop.

flymake.el depends on emacs standard library compile.el, not yours. But flymake.el loads your compile.el by your load-path priority. Please don't name same as standard package.

**Comment by artukrap** [comment]
@syohex Where compile.el is located?

**Comment by ramnes** [comment]
@syohex Yeah, that something I already though about, but that's not the problem here; I just renamed `compile.el` to `compile-config.el`, and it doesn't change anything. I updated the test case branch accordingly.

**Comment by syohex** [comment]
I can reproduce on Emacs 24.3-24.5. While I cannot reproduce on Emacs 25.1, 26. It looks byte-compiler issue. Byte-compile file compiled by `byte-recompile-directory` is strange on Emacs 24. It is different from byte-compiled file which is compiled at php-mode directory.

Avoiding this issue.
- Upgrade Emacs version 25 or higher versions
- Or Recompile php-mode.el
  - Move php-mode directory
  - Open dired
  - Type `B`(`dired-do-byte-compile`) and byte-compile again

**Comment by artukrap** [comment]
@syohex just installed Emacs 26 and same issue still acquires.

**Comment by syohex** [comment]
@artukrap Did you re-compile `.el` files with newer Emacs ?

**Comment by artukrap** [comment]
@syohex How do you exactly do that?

**Comment by syohex** [comment]
1. Uninstall php-mode
2. Install php-mode again

**Comment by Fuco1** [comment]
I'm getting this even when I clone the repo manually with git.  All the way back to 1.10 (which is the oldest tag)

**Comment by zonuexe** [comment]
If you still have the same problem with the `make` command provided by PHP Mode, reopen it.
