### ISSUE TITLE
Heredocs make buffer unresponsive

### ISSUE THREAD

**Issue by rymndhng** [emacs-php/php-mode#277]
I see this in the echo area, and it makes the buffer unresponsive.

```
Error running timer 'show-paren-function': (error "parse-sexp-propertize-function did not move syntax-propertize--done")
```

**Comment by ejmr** [comment]
Could you please post an example of a specific heredoc which causes this problem?  I cannot duplicate with any PHP files I have around that have heredoc's in them.

**Comment by syohex** [comment]
Code of that error message was introduced at http://git.savannah.gnu.org/cgit/emacs.git/commit/src/syntax.c?id=ab21f61a552f038485d40218dfd94a16b843eb52 (2015/SEP/09). Could you check to reproduce with latest development version if feasible ? There are some commits around there.

**Comment by rymndhng** [comment]
I see this happening if the `heredoc` is within a function, for example:

```
function foo() {
    var $foo = <<<EOF
   // at this point, emacs starts complaining about parse-sexp-propertize-function
}
```

I don't see this issue inside an `if` block or outside of any blocks.

**Comment by ejmr** [comment]
@rymndhng Thanks for the example.  I'm able to reproduce the problem now.

**Comment by syohex** [comment]
I don't get this error with latest version. Could you test this issue with latest version ?

**Comment by sphakka** [comment]
Upgraded recently to Emacs-25.2.1 and started observing sluggish response when editing a long HTML heredoc snippet (~120 lines, inside a function, a bit abused, I know...). No error shown, though. Really annoying :-(

**Comment by ejmr** [comment]
@sphakka Would it be possible for you to post, i.e. on a file-sharing site, a copy of a file that is causing sluggish behavior?  That would help us with testing.

**Comment by sphakka** [comment]
[Here it is](https://cloud.woelkli.com/s/E8QX2YzhjepewEh). The funny thing is that right now it works smoother... BTW, the problem shows up at the first character entered inside the heredoc snippets: observe a delay (cursor stuck for a fraction of second). Then it's OK until you jump somewhere else inside the heredoc and edit. `php-mode` is at version 20170609.1728.

**Comment by zonuexe** [comment]
Please reopen if it occurs again.
