### ISSUE TITLE
Hack Support

### ISSUE THREAD

**Issue by ejmr** [emacs-php/php-mode#278]
I would like to hear everyone's thoughts about implementing support for [Hack](http://hacklang.org/).  Obviously this would be a long-term process of implementation and testing.  These are the features I currently have in mind to implement (many related to syntax-highlighting):
1. Recognizing `<?hh`.
2. Allowing generic type-hints for arrays, e.g. `array<T>` and `array<KEY-TYPE, VALUE-TYPE>`.
3. `async` and `await`.
4. `$foo = Vector {1, 2, 3};`
5. `$foo = Map {"foo" => 1, "bar" => 2};`
6. `$foo = Set {"A", "B"};`
7. `$foo = Pair {1, "Foo"};`
8. [Enums](http://docs.hhvm.com/manual/en/hack.enums.php).
9. [Generics for classes](http://docs.hhvm.com/manual/en/hack.generics.php).
10. [Modes](http://docs.hhvm.com/manual/en/hack.modes.php).
11. [Lambdas](http://docs.hhvm.com/manual/en/hack.lambda.php) using the `==>` syntax.
12. [Nullable types](http://docs.hhvm.com/manual/en/hack.nullable.php).

13 [Shapes](http://docs.hhvm.com/manual/en/hack.shapes.php) and [type aliases](http://docs.hhvm.com/manual/en/hack.typealiasing.php).

**Comment by zonuexe** [comment]
Hack lang has become a separate language and now [hhvm/hack-mode](https://github.com/hhvm/hack-mode) is actively being developed.
