### ISSUE TITLE
Feature request: Indentation in php-html mixed mode

### ISSUE THREAD

**Issue by marcinant** [emacs-php/php-mode#32]
Php-mode doesn't work with current mmm-mode https://github.com/purcell/mmm-mode
(font-lock is broken, indentation behave in random way )

I've been trying to use this with multi-web-mode https://github.com/fgallina/multi-web-mode

It's also broken. Indentation doesn't work at all. It generates random "a" in front of each empty line etc.

And mmm-mode and multi-web-mode goes crazy when facing syntax like this one (from WordPress theme):

<body <?php body_class(); ?> >

Could it be possible to implement internal indentation rules for html in php-mode? 
Css and js code usually goes to separate files and doesn't mix with php. But html is a different story.

**Comment by nickenchev** [comment]
I don't like to mix PHP with HTML either, but the previous developer on my current project seemed to love doing it. So when I first opened the PHP files with Emacs, I was a little shocked at how broken things were. I find it odd that there would be an argument against this feature based purely based on ideology, as there are obviously a ton of PHP projects in the wild that mix content. Whether or not we agree if that is a good practice is irrelevant.
