### ISSUE TITLE
Switch to the rx Macro Where Possible

### ISSUE THREAD

**Issue by ejmr** [emacs-php/php-mode#354]
Reviewing 56a7e7c67b70c4aba5919317a8898157ba0b08e4 made me start to think all of our regular expressions have built up too many backslashes and parentheses.  I think we should consider rewriting them in terms of `rx`; [here is an explanation of the macro](http://francismurillo.github.io/2017-03-30-Exploring-Emacs-rx-Macro/).  Anyone wanting full details can `C-h f rx <RET>` in Emacs itself.  `rx` is surprisingly absent from the Emacs Lisp manual.

**Comment by zonuexe** [comment]
:+1:

**Comment by zonuexe** [comment]
Now this suggest is our policy.
