### ISSUE TITLE
Ownership Transfer

### ISSUE THREAD

**Issue by ejmr** [emacs-php/php-mode#387]
Per the discussion in #365, I intend to hand over ownership of PHP Mode to [the emacs-php group](https://github.com/emacs-php), in the sense of "owning" and controlling the project here on GitHub.

@zonuexe: You are the best person to be the maintainer of PHP Mode, in my opinion.  If you are still interested in taking that role, how would you like to proceed?  Two options jump to mind:

1. I change the GitHub project settings to give ownership to @emacs-php, which would involve changing various links throughout the project to (something like) `https://github.com/emacs-php/php-mode`.  Most importantly, it would involve changing the URL for package repositories like MELPA so that they point to the actively maintained repository.

2. I can simply give you my GitHub account login.  That idea will sound ridiculous to some people, but I honestly would be perfectly fine with it.  I do not intend to do anymore public programming for the remainder of my life, so the idea of someone else having my account info---especially someone I respect and trust implicitly---is completely fine with me.

The first option is probably the best, while the second option is the laziest, heh.

Or we could leave the project settings as they are for now, with you as a "collaborator" (in GitHub terms) and instead update the README to reflect that the emacs-php group, i.e. you, are now the maintainer(s), and remove my name from the maintainer list; I feel like it would also be appropriate to no longer list @syohex as one of the core maintainers either, because like myself, he no longer has the time to dedicate to the project.  Regardless, if we take this approach then at some point in the future you could clone this project under the @emacs-php account and then submit pull-requests to places like MELPA so that they point to that repository and not this one, and in the mean time continue to use this copy of the repository for maintenance and work.

I would be happy with any of those options, or any others which you may have in mind.  Let me know what you would prefer and I will oblige.

**Comment by zonuexe** [comment]
@ejmr Thank you for suggesting various methods.

I think that it is the best way to simply transfer ownership to @emacs-php.
I never feel that it is a burden to inherit the maintainer and ownership position of PHP Mode.

And even if you abandon your GitHub account, no one can blame you.  All users of PHP Mode are grateful to you and the previous developers.  Please use your time for yourself.

**Comment by ejmr** [comment]
[Per the documentation](https://help.github.com/articles/transferring-a-repository/), I cannot transfer the repository to @emacs-php because I do not have permissions, i.e. the appropriate permissions as being part of @emacs-php organization itself.  In order to transfer the repository I am 99% sure that I will have to be made a "collaborator" or member of @emacs-php first.

**Comment by zonuexe** [comment]
@ejmr I added you as an owner.

**Comment by ejmr** [comment]
@zonuexe So fast, heh.  Thanks!

**Comment by Fuco1** [comment]
FYI I've done this in the past and all the links still work so long as you do not deactivate your account (so that someone else can grab it and start a new project under that "namespace").  So even after the transfer MELPA can still fetch from the "ejmr" namespace even if the repo is under the org.

So updating all the external links is not strictly necessary in the beginning of the transfer process and can be handled on the fly.

**Comment by hexmode** [comment]
@zonuexe: Can this be closed now?

**Comment by zonuexe** [comment]
@hexmode Why?

**Comment by hexmode** [comment]
Ownership has been transferred, hasn't it?  The list of maintainers updated, etc.

**Comment by ejmr** [comment]
In my opinion @hexmode is right and we can close this, although as the maintainer I leave that to you @zonuexe, of course.  Also if I make it to PHPCon in Japan this December, can we get a photo of me literally handing you a box with "PHP Mode" written on it and then post it here to finish this thread?  Heh.

`</DumbHumor>`

`--ejmr`

**Comment by zonuexe** [comment]
BTW, this GitHub repository still belongs to https://github.com/ejmr, so Debian's Emacsen Team seems to negotiate to @ejmr in #473. Can you transfer ownership of this repository to @emacs-php?

**Comment by ejmr** [comment]
@zonuexe 

The repository should be transferred now, although I got a message that it may take a few minutes (from the time of this comment).  Please let me know if it fails for some reason.

**Comment by zonuexe** [comment]
@ejmr Thank you, there seems to be no problem.

There is no problem with the link from https://melpa.org/#/php-mode .

**Comment by zonuexe** [comment]
I will send a PR for correction to MELPA later.
