### ISSUE TITLE
Unmatched double quote inside single quotes breaks font lock.

### ISSUE THREAD

**Issue by bryan-kramer** [emacs-php/php-mode#390]
This starting happening recently.

```
  php-mode           20171107.826  available  melpa      Major mode for editing PHP code
```

Example code (not realistic code but it illustrates the point):

     <?php
     $x = 'a"' . $hello . '"';

     foreach ($items as $item) {
     }

looks like
![image](https://user-images.githubusercontent.com/3759834/32803497-ae97e836-c951-11e7-91ae-8dfffba57222.png)

```
Enabled minor modes: Abbrev Auto-Composition Auto-Compression
Auto-Encryption Delete-Selection Diff-Auto-Refine File-Name-Shadow
Font-Lock Global-Eldoc Global-Font-Lock Line-Number Menu-Bar
Mouse-Wheel Show-Paren Tool-Bar Tooltip Transient-Mark

(Information about these minor modes follows the major mode info.)

PHP/* mode defined in ‘php-mode.el’:
Major mode for editing PHP code.

```

**Comment by fallchildren** [comment]
Is this still a problem with current php-mode master?

**Comment by Ramapitecus** [comment]
I've tested this using emacs 27.0.50 (compiled from source) and php-mode 1.18.4 and it's fixed. Came here for the same issue. Updated and tested.
