### ISSUE TITLE
php-mode executes c-mode hooks

### ISSUE THREAD

**Issue by NateEag** [emacs-php/php-mode#407]
I recently added [cquery](https://github.com/cquery-project/cquery) to my c-mode setup, which meant adding a `c-mode-hook` to start cquery.

Doing that broke my ability to open PHP files sanely, because cquery starts itself before my [lsp-php](https://github.com/tszg/lsp-php) instance gets a chance to start, resulting in a broken state. Since they're both [lsp-mode](https://github.com/emacs-lsp/lsp-mode) plugins, each targeting a specific language, it makes sense that they conflict.

I gather that php-mode is derived from c-mode, and therefore runs c-mode's hooks. I've worked around this problem by only starting cquery when `(equal major-mode 'c-mode)`, but it doesn't seem like I should have to do that.

[This StackOverflow question](https://stackoverflow.com/questions/42982838/emacs-c-mode-hook-runs-when-opening-a-php-file) shows a similar problem and workaround.

The answer there points out that `c-mode` and friends actually derive from prog-mode, and suggests that php-mode should probably do that too. A quick search of cc-mode.el in Emacs 25.3.1 for `define-derived-mode` shows that is in fact how `cc-mode.el` currently does things.

I looked for any existing issues or discussion around this point, but I wasn't able to find any. I did find [this thread](https://github.com/ejmr/php-mode/issues/291) with some discussion about the move to basing php-mode on cc-mode in the first place.

Should we consider extending `prog-mode` rather than `c-mode`? 

If so, how much work would that involve?

**Comment by fallchildren** [comment]
Could you check this branch in my repo? https://github.com/fallchildren/php-mode/tree/prog-mode-derived This seems to do it (2 lines changed as we just need the syntax table from c-mode). But seems to introduce a font-locking bug in emacs 25 regarding comments (The comment test fails). Which is fixed in conjunction with my Pull-Request #401. @syohex Would it be okay to add this as a pull request but only with the pre condition of #401 merged?

I haven't tested this thoroughly though.

**Comment by NateEag** [comment]
@fallchildren That change does resolve my hook problem. Thanks!

I can see the font-lock bug you're talking about, and I haven't tested it thoroughly either.

I probably can use it for a daily driver for a while if/when #401 lands and see if it causes me any issues.

**Comment by fallchildren** [comment]
@zonuexe What's your thought on this?

**Comment by zonuexe** [comment]
I think it is better to bypass `(define-derived-mode cc-mode)` as well.
`js-mode` is a good model for us, it uses the function of `cc-mode`, but bypassed inheritance.
https://github.com/emacs-mirror/emacs/blob/973d10a34b23f2ce5acc00a90ec9767e6237fefa/lisp/progmodes/js.el#L3858

I think this method is correct, I agree to refactor `php-mode` as that way.

@fallchildren 
I will be able to undertake that change in the next leisure, but it will probably take some time.
Can you make this refactor?

**Comment by fallchildren** [comment]
@zonuexe I can try... a very simple approach is in #409. This one does get rid of the derived-mode but not of `(c-add-language 'php-mode 'java-mode)` and all the calls to `c-lang-defconst` which `js-mode` does not use. You would want to get rid of those as well as shown in `js-mode,` right?

**Comment by ejmr** [comment]
The command `git grep "cc-mode"` will be a fast way to find most of what will need careful re-testing after any switch to `prog-mode`, `js-mode`, etc.

**Comment by zonuexe** [comment]
@NateEag 
This problem was solved by #492. This change will be released as `v1.21.0`.

**Comment by NateEag** [comment]
@zonuexe Awesome. Thanks for the heads-up!
