### ISSUE TITLE
Heredoc/Nowdoc highlighting issue

### ISSUE THREAD

**Issue by zonuexe** [emacs-php/php-mode#439]
Since this pattern consists of `\w+`, consideration to `_` is missing.  Moreover, it does not correspond to the `<<<"heredoc"` style.

<img width="152" alt="2018-03-10 0 53 23" src="https://user-images.githubusercontent.com/822086/37216168-7d482ca8-23fd-11e8-8f5c-e0e13b438dec.png">

<img width="159" alt="2018-03-10 0 55 02" src="https://user-images.githubusercontent.com/822086/37216252-b66b1efa-23fd-11e8-9d61-84f75b80c2ba.png">

**Comment by efermi** [comment]
Nowdoc highlighting breaks for me in this file, it seems that the cause is somewhere in the preceding comment.
![Screenshot_20210422_030816](https://user-images.githubusercontent.com/3966555/115637214-478e9000-a318-11eb-8f8c-ad6379c860c8.png)
```php
<?php

/*
 * # Log file format version (1.0/1.1) 1.1 adds the MusicBrainz Track ID column, specifies UTF-8 encoding of strings.
 * # Time zone (UTC|UNKNOWN) If the device knows its timezone it logs the timestamps in UTC, otherwise they TZ-less and need correction.
 * # Device ID
 * Body (one line per track):
 * | Artist | [Album] | Track | [Track #] | Duration (seconds) | Rating | Timestamp | [TrackID] |
 * If an optional field has no data it is left blank (\t\t)
 * UTF-8 w/o BOM
 */

$play_log = <<<'LOG'
#AUDIOSCROBBLER/1.1
#TZ/UNKNOWN
#CLIENT/Rockbox sansaclipplus $Revision$
Art Blakey and The Jazz Messengers	Moanin'	Moanin'	1	575	L	1616975543
Art Blakey and The Jazz Messengers	Moanin'	Are You Real	2	290	S	1616976122
Art Blakey and The Jazz Messengers	Moanin'	Along Came Betty	3	372	S	1616976132
Art Blakey and The Jazz Messengers	Moanin'	The Drum Thunder Suite	4	455	L	1616976134
Art Blakey and The Jazz Messengers	Moanin'	Blues March	5	378	L	1616976589
Art Blakey and The Jazz Messengers	Moanin'	Come Rain or Come Shine	6	348	L	1616976967
LOG;

$API_ENDPOINT = 'http://ws.audioscrobbler.com/2.0/';
$API_KEY = '';
$API_SHARED_SECRET = '';

```

**Comment by zonuexe** [comment]
@efermi 
Thank you for reporting. I reproduced the problem in my environment.

This is certainly similar to the existing problem, but the situation is a bit complicated.

<img width="1140" alt="スクリーンショット 2021-04-22 10 27 05" src="https://user-images.githubusercontent.com/822086/115642204-7aa34480-a355-11eb-8657-8caa1ab92b9d.png">
<img width="1104" alt="スクリーンショット 2021-04-22 10 27 21" src="https://user-images.githubusercontent.com/822086/115642213-7ecf6200-a355-11eb-9e91-bded2bc7c648.png">

This looks like a problem with the PHP Mode coloring algorithm, so I'll find and investigate a lot of time.

**Comment by efermi** [comment]
Thank you for looking into it.

**Comment by zonuexe** [comment]
It looks fine in Emacs 28 and above.
