### ISSUE TITLE
backtrace on un-balanced quotes

### ISSUE THREAD

**Issue by hexmode** [emacs-php/php-mode#474]
emacs version: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-06-08, unofficial emacs-snapshot build: http://emacs.ganneff.de/, git commit f09e9d292f31abeac37e83c3558d7b33a6a1abbf

php-mode.el: latest from git

gif illustrating problem after starting an `emacs --no-site-file -q`, adding php-mode to the load path and turning on `toggle-debug-on-error` and opening an empty, previously non-existant tmp.php:

![shortest](https://user-images.githubusercontent.com/43581/43217212-fcc9531c-900e-11e8-82f0-602eacf979dc.gif)

Backtrace generated:
```
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  search-forward-regexp(nil nil t)
  c-after-change-re-mark-unbalanced-strings(17 18 0)
  #f(compiled-function (fn) #<bytecode 0x529be9>)(c-after-change-re-mark-unbalanced-strings)
  mapc(#f(compiled-function (fn) #<bytecode 0x529be9>) (c-depropertize-new-text c-after-change-re-mark-unbalanced-strings c-change-expand-fl-region))
  c-after-change(17 18 0)
  self-insert-command(1)
  funcall-interactively(self-insert-command 1)
  call-interactively(self-insert-command nil nil)
  command-execute(self-insert-command)
```

**Comment by zonuexe** [comment]
@hexmode Thank you for reporting.

I confirmed that this problem does not occur in Emacs 26.
I will probably investigate this problem tomorrow or the day after tomorrow.

**Comment by hexmode** [comment]
I was so aggrivated by this that I ended up compiling the git master myself (since I've had trouble upgrading the emacs-snapshot package).

With the code on master today, this no longer happens.

**Comment by ejmr** [comment]
@hexmode 

Great job on providing such useful information about the bug.  I am glad it is magically fixe by compiling the latest version of GNU Emacs.  I agree this issue should be closed, but I also implore you and @zonuexe  to eventually discover this bug; but I do not consider it a high priority either.

I know lately we've been talking about a list of priorities, hence my comment.

`--ejmr`

**Comment by hexmode** [comment]
My thought was only that this was a bug in `cc-mode`.  [This fix from July 8th](https://github.com/emacs-mirror/emacs/commit/fe06f643b2808b198bb58bda04a8c863e55a2a56#diff-d0c72e3b0fda6f909002e7f20517c5c2) looks like a good candidate as does [this one from May 20th](https://github.com/emacs-mirror/emacs/commit/bb591f139f0602af292c772f974dcc14dabb1deb#diff-d0c72e3b0fda6f909002e7f20517c5c2).

Those are the ones that affected `c-after-change-re-mark-unbalanced-strings` since my previous update, but I'm sure there are other place to look.

**Comment by hexmode** [comment]
doh, I just realized that the build I was using was from June 8th.  So I imagine the first fix I mentioned was it.

**Comment by hexmode** [comment]
Confirmed.  I reverted only that change from emacs master and the bug showed up again.
