### ISSUE TITLE
manual install instructions incorrect

### ISSUE THREAD

**Issue by robnagler** [emacs-php/php-mode#501]
README is incorrect:

> download the php-mode.el file, place it inside your load-path

You also need php-project.el, would be good to include more info as well:

download [php-mode.el](https://raw.githubusercontent.com/emacs-php/php-mode/master/php-mode.el) and [php-project.el](https://raw.githubusercontent.com/emacs-php/php-mode/master/php-project.el), install in your load-path (e.g. `~/.emacs/lisp`)

**Comment by sergeyklay** [comment]
To get the latest version of php-mode go to PHP Mode’s GitHub page, switch to the upstream branch (currently `master`):
```
https://github.com/emacs-php/php-mode/tree/master
```

Download the latest version either via git or direct download:
```sh
$ wget https://github.com/emacs-php/php-mode/archive/master.zip
$ unzip master.zip
```

Move `php-mode-master` to your Emacs Lisp path (eg.`site-lisp`)
```sh
$ mv php-mode-master ~/.emacs.d/site-lisp/php-mode
```
Add `php-mode` to the load path:
```emacs-lisp
(add-to-list 'load-path
             (concat (file-truename user-emacs-directory) "site-lisp/php-mode/"))
```

Load/require `php-mode.el` `php-project.el`.

The same works for formal, tagged releases.

**Comment by zonuexe** [comment]
@robnagler @sergeyklay 
I am sorry for not replying to this issue. My recommended introduction method was explained in #515.

As I am a Japanese speaker and I am not good at English, please cooperate to make this document easier to understand. Thank you!

**Comment by zonuexe** [comment]
Installation instructions are documented in [Manual installation · emacs-php/php-mode Wiki](https://github.com/emacs-php/php-mode/wiki/Manual-installation). Feel free to suggest any ideas for improvement. thank you!
