### ISSUE TITLE
Failing test for issue 443 on emacs 27

### ISSUE THREAD

**Issue by mallt** [emacs-php/php-mode#524]
The test for issue 443 fails on emacs 27 (an on emacs-git-snapshot-travis) because`*/` is considered separately as a comment delimiter. This is the difference in the output of the ert test:

<img width="661" alt="afbeelding" src="https://user-images.githubusercontent.com/8885691/57947992-c2570100-78e0-11e9-8a4a-997feaaa5ae0.png">

@zonuexe Do you know an easy way to make this test pass on emacs 27? We could make a separate `issue-443-emacs-27.php` and `issue-443-emacs-27.php.faces` and then check the emacs version when running the tests, but I hope there is a more elegant solution. :)

Thanks!

**Comment by zonuexe** [comment]
@mallt  Thank you for raising an issue.
If you don't have a lot of problems, I want to work around with the following quick hacks #526.
If this solution is difficult, let's find another one.

Thank you!
