### ISSUE TITLE
Support Property Accessor Syntax

### ISSUE THREAD

**Issue by ejmr** [emacs-php/php-mode#54]
PHP 5.5 introduces [property accessors](https://wiki.php.net/rfc/propertygetsetsyntax-v1.2).  So php-mode needs to accomodate for these, at least in terms of syntax highlighting if nothing else.

**Comment by kalifg** [comment]
Can this be closed since the RFC was never accepted?

**Comment by zonuexe** [comment]
@kalifg Since [Typed Properties 2.0](https://wiki.php.net/rfc/typed_properties_v2) was accepted, [Property Accessors Syntax 1.2](https://wiki.php.net/rfc/propertygetsetsyntax-v1.2) will probably not be re-proposed.
