### ISSUE TITLE
`php-style-delete-trailing-whitespace` error when entering mode

### ISSUE THREAD

**Issue by wavexx** [emacs-php/php-mode#553]
On recent builds of emacs (from git), I now get an error when entering php-mode:

```
Debugger entered--Lisp error: (void-variable php-style-delete-trailing-whitespace)
  php-set-style("nil")
  php-mode()
  set-auto-mode-0(php-mode nil)
  set-auto-mode()
  normal-mode(t)
  ...
```

https://github.com/emacs-php/php-mode/blob/9e6e148c5ea8dc765b943f90e6012b667c39f906/php-mode.el#L1034

**Comment by zonuexe** [comment]
@wavexx 
Perhaps errors were suppressed, but I am concerned about `(php-set-style " nil ")`.
Did you set the `php-mode-coding-style` variable?

**Comment by wavexx** [comment]
On Thu, Aug 01 2019, USAMI Kenta wrote:
> Perhaps errors were suppressed, but I am concerned about (php-set-style " nil ").
> Did you set the php-mode-coding-style variable?

Yes, I had it set to nil instead of 'default at some point (this is an
old config - so I'm not sure when I did that years ago).
