### ISSUE TITLE
Indentation in function fails if file has variable assignment before

### ISSUE THREAD

**Issue by cweiske** [emacs-php/php-mode#554]
Example:
```
<?php
$a = false;

function foo()
{
$b = 'b';
}
```

`$b` gets indented to column 0, which is wrong.

When I remove the first line (`$a = false;`), indentation inside the function works.

**Comment by zonuexe** [comment]
@cweiske Can you provide us output of `M-x php-mode-debug`?

**Comment by cweiske** [comment]
I'm sorry. I tried my test file again and now it works correctly.
I cannot explain why it did not work 2 days ago.

Sorry for the trouble.
