### ISSUE TITLE
Indentation of string concatenation fails inside closure

### ISSUE THREAD

**Issue by cweiske** [emacs-php/php-mode#555]
When a string is concatenated on multiple lines inside a closure, the indentation is wrong on the second line if the first line contains a concatenating dot:

```
<?php
someClosureHandling(
    function () {
        return 'a' . 'b'
                   . 'c';
    }
);
```

`. 'c';` should be indented 4 characters relative to `return`, and not on the same position as the dot in the line above.

Should be:
```
<?php
someClosureHandling(
    function () {
        return 'a' . 'b'
            . 'c';
    }
);
```

**Comment by zonuexe** [comment]
Resolved in https://github.com/emacs-php/php-mode/pull/777.
