### ISSUE TITLE
Font lock problems in emacs snapshot

### ISSUE THREAD

**Issue by gjm** [emacs-php/php-mode#562]
Running on emacs snapshot I have some font-lock/syntax highlight issues: some keywords are not properly shown (the `use`, `extends` and `function` keywords). Also, strings in single quotes are also not properly shown.

I've attached two screenshots, one from stable build and one from snapshot build, highlighting the issues.

stable version:
![stable](https://user-images.githubusercontent.com/77360/63218044-7fa7fd80-c149-11e9-920c-161e97c8fa56.png)

snapshot version:
![snapshot](https://user-images.githubusercontent.com/77360/63218049-8fbfdd00-c149-11e9-9cd7-b0c7ca9bd9a9.png)

**Comment by zonuexe** [comment]
@gjm Thank you for reporting.

**Comment by mallt** [comment]
@gjm Do you notice any logging of errors in the `*Messages*` buffer in the snapshot version?

**Comment by gjm** [comment]
@mallt yes
```
Eval error in the ‘c-lang-defvar’ or ‘c-lang-setvar’ for ‘c++-template-syntax-table’ (fallback source eval - php-mode compiled with CC Mode 5.33.1 but loaded with 5.34): (error "‘c++-make-template-syntax-table’ got no (prior) value in php-mode (might be a cyclic reference)")
```

I'm sorry I hadn't noticed it before and mentioned it in the initial report.

**Comment by mallt** [comment]
@gjm Ok thanks! Can you try to delete and reinstall the php-mode package? I think that should fix this error.

**Comment by gjm** [comment]
@mallt Yes it seems to be OK. 

Thanks!

**Comment by zonuexe** [comment]
@gjm @mallt Great, thank you both!
