### ISSUE TITLE
Add '$' to symbol-constituting characters

### ISSUE THREAD

**Issue by tomterl** [emacs-php/php-mode#564]
Is there a reason /not/ to add '$' to the characters constituting a symbol in a php-mode buffer?  I added 

    (modify-syntax-entry ?$ "_")

to my php-mode hook to get dap-mode mouse-hover to work, showing the variable/symbol under point 's current value during a debug-session in a tooltip or the echo-area.

My search for a previous discussion came up emtpy.

**Comment by zonuexe** [comment]
This suggestion is the same as #320 , but my opinion has changed in the last few years.

I would like to change this syntax-entry in the next release.

@mallt How about this?

**Comment by mallt** [comment]
@zonuexe @tomterl Yes I agree, thank you!
