### ISSUE TITLE
Symbol’s function definition is void: rx-form

### ISSUE THREAD

**Issue by slk500** [emacs-php/php-mode#579]
I just installed newest version of GNU Emacs 27.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) and got this error with php-mode "Error (use-package): php-mode/:catch: Symbol’s function definition is void: rx-form". How I can fix this?

**Comment by zonuexe** [comment]
@slk500 Thank you for reporting, the issue was resolved in https://github.com/emacs-php/php-mode/pull/580.
