### ISSUE TITLE
Faces for operators and certain functions

### ISSUE THREAD

**Issue by minikN** [emacs-php/php-mode#582]
Hello, I've setup the php-mode faces like this:

```
   (php-function-name				 :foreground green)
   (php-function-call				 :foreground green)
   (php-string 					 :foreground yellow)
   (php-keyword 				 :foreground red)
   (php-builtin 				 :foreground purple)
   (php-method-call 				 :foreground green)
   (php-static-method-call 			 :foreground green)
   (php-variable-name 				 :foreground fg)
   (php-property-name 				 :foreground fg)
   (php-variable-sigil 				 :foreground fg-2)
   (php-object-op 				 :foreground red)
   (php-paamayim-nekudotayim 			 :foreground red)
   (php-type 					 :foreground blue :slant italic)
   (php-class 					 :foreground blue)
   (php-constant 				 :foreground purple)
   (php-constant-assign 			 :foreground blue)
   (php-magical-constant 			 :foreground purple)
   (php-$this 					 :foreground fg-2)
   (php-$this-sigil				 :foreground fg-2)
   (php-errorcontrol-op 			 :foreground red)
   (php-doc-annotation-tag 			 :foreground blue)
   (php-doc-variable-sigil 			 :foreground fg-4)
   (php-doc-$this 				 :foreground fg-4)
   (php-doc-$this-sigil 			 :foreground fg-4)
   (php-doc-class-name 				 :foreground fg-4)
```

However, certain functions are still being displayed in white, like `define`, `substr`, `array_merge` and probably many more.

Is there a way to change their face(s)?

Further more, can I change faces for operators? Bascially everything defined here: https://github.com/emacs-php/php-mode/pull/536/files

They are also white currently.

Thanks.

**Comment by minikN** [comment]
Hello,

is this supposed to work after the merge?
If I customize the font `php-operator` to red, operators, in my code (`=`, ...) still appear white.

**Comment by zonuexe** [comment]
@minikN 
> is this supposed to work after the merge?

No. As you can see from the difference in #583, only `php-function-call` is implemented.
Other faces are just  reserved.

I don't have enough time to work on it, but when I receive the patch, I can merge it.

**Comment by minikN** [comment]
Ohh, I get it. Sorry then!

**Comment by minikN** [comment]
#594 

Hello. I've created a PR to implement support for the operators. Neither lisp nor regex is my strong suite, so this might not be up to your standard, but as far as I can tell - it's working.

Cheers.
