### ISSUE TITLE
c-evaluate-offset: Wrong type argument: integer-or-marker-p, (856 881 880 881 #<buffer Batch.php>)

### ISSUE THREAD

**Issue by xendk** [emacs-php/php-mode#586]
The fix for #584 causes an error:

![image](https://user-images.githubusercontent.com/229422/68551584-bb7ff580-040e-11ea-8619-48763aa66ed4.png)

That's on trying to indent the last two lines of the function from the screenshot it #584..

**Comment by xendk** [comment]
Oh, and  `php-c-lineup-arglist: Invalid search bound (wrong side of point)` everwhere else.

**Comment by xendk** [comment]
I've added additional information on the linked issue.

**Comment by zonuexe** [comment]
@xendk Thank you for reporting.

**Comment by xendk** [comment]
@zonuexe thank you for fixing.
