### ISSUE TITLE
Use empty face instead of inheriting default

### ISSUE THREAD

**Issue by cyrus-and** [emacs-php/php-mode#595]
Many faces used by this mode inherit the `default` face, this has the unpleasant consequence that the background is reset in Markdown code blocks with custom background, see for example:

![2019-12-06_19-21](https://user-images.githubusercontent.com/1660263/70346044-abb4cf00-185d-11ea-81af-f68ab326188f.png)

My solution is to do something like this:

```lisp
(custom-set-faces
 `(php-arithmetic-op ((t ())))
 `(php-assignment-op ((t ())))
 `(php-comparison-op ((t ())))
 `(php-function-call ((t ())))
 `(php-object-op ((t ())))
 `(php-paamayim-nekudotayim ((t ())))
 `(php-static-method-call ((t ())))
 `(php-variable-sigil ((t ()))))
```

But the list is growing longer and longer... Would it be possible to avoid inheriting the `default` face and use an empty face instead? Would there be any drawbacks?

**Comment by zonuexe** [comment]
@cyrus-and  Thank you for your suggestion. 
The `(:inherit default)` was not important, so I didn't know its side effects.

Let's remove it.

**Comment by cyrus-and** [comment]
Awesome, thank you! Tested and it works.
