### ISSUE TITLE
How do you join the emacs-php group?

### ISSUE THREAD

**Issue by cjohansson** [emacs-php/php-mode#645]
I'm an active Emacs + PHP developer and would like to help out where I can

**Comment by zonuexe** [comment]
I'm sorry, I haven't seen this issue because I've been busy with work for the past month. I know your job and welcome your suggestions!

**Comment by zonuexe** [comment]
I invited @cjohansson  as a member of https://github.com/emacs-php .

**Comment by cjohansson** [comment]
Thanks!

**Comment by NateEag** [comment]
@zonuexe I'm also an active Emacs + PHP user, and while most of my spare time goes to parenting small kids these days, I have wondered before about joining the `emacs-php` organization.

Is there any kind of application process?

I haven't done much OSS work in recent years, but I have made a few contributions to PHP, Emacs, and web-related OSS projects in the past:

I fixed [an lsp-mode bug to get the `php-language-server` project working with it](https://github.com/emacs-lsp/lsp-mode/issues/119).

I [improved emmet-mode's ability to swap between HTML or CSS abbreviations contextually](https://github.com/smihica/emmet-mode/pull/15).

I [added some features to php-auto-yasnippet](https://github.com/emacs-php/php-auto-yasnippets/pull/16).

I [added support for dynamic auto-complete sources to web-mode](https://github.com/fxbois/web-mode/issues/116).

I also [added support for branch names with slashes to gitlist](https://github.com/klaussilveira/gitlist/pull/259).

I don't have lots of time for OSS right now, so I wouldn't make many contributions right now, but I figured it was worth asking, as in principle I'd like to help and have made contributions to related things in the past.

**Comment by zonuexe** [comment]
@NateEag Thank you for your interest. I have seen you contribute to several projects so far.

This @emacs-php team is not yet organized and was set up solely to ensure that Lisp package development is not interrupted by personal circumstances. That's why we're trying to increase the number of members and maintainers. Of course we welcome your offer.

I invited @NateEag as a member of https://github.com/emacs-php.

**Comment by NateEag** [comment]
@zonuexe Cool. I've had similar concerns about single points of failure for packages. Thanks so much!
