### ISSUE TITLE
Dependency on specific version of nadvice.el

### ISSUE THREAD

**Issue by bkline** [emacs-php/php-mode#682]
I'm running emacs 24.3.1 on a shared hosting site, and I followed the instructions for installing `php-mode` manually. The first time the mode was invoked, the loader complained that it couldn't find the `nadvice` package. So I used the package manager to install that dependency and tried again. This time I got the error message:
```
File mode specification error: (error "This version of nadvice.el does not support PROPS")
```
So what's the missing piece of information which is needed here? The `php-mode` is from the current `master` branch.

**Comment by zonuexe** [comment]
@bkline 
PHP Mode no longer has active support for Emacs 24.  Please use [v1.23.0](https://github.com/emacs-php/php-mode/releases/tag/v1.23.0) or [v1 branch](https://github.com/emacs-php/php-mode/tree/v1) by [Manual installation](https://github.com/emacs-php/php-mode/wiki/Manual-installation).
See [#592 Drop Emacs 24 Support](https://github.com/emacs-php/php-mode/issues/592) and [Supported Version · emacs-php/php-mode Wiki](https://github.com/emacs-php/php-mode/wiki/Supported-Version) for details.

**Comment by bkline** [comment]
Thanks!
