### ISSUE TITLE
Missing Contributors in AUTHORS.md

### ISSUE THREAD

**Issue by Shamar** [emacs-php/php-mode#685]
Hi, I've just noticed that most of old php-mode.el contributors are not listed in the AUTHORS.md file.

Here the list from https://sourceforge.net/p/php-mode/code/HEAD/tree/trunk/php-mode-src/php-mode.el#l61

```
;;; Contributors: (in chronological order)

;; Juanjo, Torsten Martinsen, Vinai Kopp, Sean Champ, Doug Marcey,
;; Kevin Blake, Rex McMaster, Mathias Meyer, Boris Folgmann, Roland
;; Rosenfeld, Fred Yankowski, Craig Andrews, John Keller, Ryan
;; Sammartino, ppercot, Valentin Funk, Stig Bakken, Gregory Stark,
;; Chris Morris, Nils Rennebarth, Gerrit Riessen, Eric Mc Sween,
;; Ville Skytta, Giacomo Tesio, Lennart Borgman, Stefan Monnier,
;; Aaron S. Hawley, Ian Eure, Bill Lovett, Dias Badekas, David House
```

**Comment by zonuexe** [comment]
@Shamar Thank you for your notice!  I'm sorry I missed your PR for a long time.

**Comment by zonuexe** [comment]
note:

I ported Contributors in [Pull Request #607](https://github.com/emacs-php/php-mode/pull/607/files), but I wasn't aware that many contributors were missing.
