### ISSUE TITLE
Please tag release (prerelease or beta is ok) for Emacs 28 compatibility

### ISSUE THREAD

**Issue by sten0** [emacs-php/php-mode#700]
Hi,

Debian has recently imported Emacs 28 and users are complaining about bugs in 1.24.0.  Would you please consider tagging a release at this time?  A prerelease or beta is of course ok, and if you would prefer, I can package a snapshot of the master branch for now :)

The deadline for uploading a recent copy of php-mode into Debian 12 "bookworm" will be January 2023.

Thank you,
Nicholas

**Comment by zonuexe** [comment]
@sten0 
Thank you for you suggestion. I bumped up to [v1.24.1](https://github.com/emacs-php/php-mode/releases/tag/v1.24.1).
