### ISSUE TITLE
PEAR method chaining wrong indentation

### ISSUE THREAD

**Issue by cweiske** [emacs-php/php-mode#745]
The PEAR coding standard says in https://pear.php.net/manual/en/standards.funcalls.php

> Using fluent application programming interfaces often leads to many concatenated function calls. Those calls may be split onto several lines. When doing this, all subsequent lines are indented by 4 spaces and begin with the "->" arrow.
```
<?php
$someObject->someFunction("some", "parameter")
    ->someOtherFunc(23, 42)
    ->andAThirdFunction();
?> 
```

On my emacs 27.1 with php-mode 20230423.1446 the second method call arrow is directly below the previous arrow (wrong): 
```
        $pages = $dbOld->createQueryBuilder()
                       ->select('*')
```

Setting `php-mode-lineup-cascaded-calls` to `nil` aligns the `->` with the `=` (wrong):
```
        $pages = $dbOld->createQueryBuilder()
               ->select('*')
```

When enabling the pear coding style, it should be indented 4 spaces:
```
        $pages = $dbOld->createQueryBuilder()
            ->select('*')
```

(Related to #237, which was the same problem with PSR2)

**Comment by cweiske** [comment]
It seems that `php-mode-lineup-cascaded-calls = nil` not working was a configuration problem in my configuration.

So the only thing left is that pear style should set that automatically.

**Comment by cweiske** [comment]
The bug does actually exist if the code has an equal sign. Wrong:
```
$pages = $foo->bar()
       ->baz();
```

I would expect this:
```
$pages = $foo->bar()
    ->baz();
```

**Comment by cweiske** [comment]
@zonuexe please reopen - only one problem is solved with #746, but not the identation-after-`=` one.

**Comment by zonuexe** [comment]
@cweiske Perhaps merging #777 resolved this issue. This problem seems to have been introduced by some strange change in the past unrelated to the PEAR Coding Standards. Please feel free to send any feedback regarding PEAR style to #776.

Thank you for your report!

**Comment by cweiske** [comment]
This is fixed - thank you!
