### ISSUE TITLE
Non-C-style comments are filled incorrectly

### ISSUE THREAD

**Issue by NateEag** [emacs-php/php-mode#76]
Consider the following set of comments:

```
// This is a test comment. If I get it to go a very long way, my autowrapping will work, but you will find that Meta-Q will
// not fill the comment correctly.

# What happens when I write a lengthy comment prefixed by the # symbol? I am not sure, but I guess I am about to find out.

/* However, something very similar will actually work exactly the way you would expect it to in a C-style comment. Any ideas why this is?
 */
```

All three are correctly highlighted as comments by php-mode.

However, if you use Meta-Q to wrap the comments, only the last comment is filled correctly. The first two are wrapped, but no comment prefix is inserted at the beginning of the new lines.

**Comment by trashofmasters** [comment]
@NateEag I've found that all three styles of comment can be indented correctly after you evaluate this form:

```elisp
;; this is the relevant bit, you'll notice it's adding # as a comment start char
(setq-local comment-start-skip "\\(//+\\|#+\\|/[*]\\{1,2\\}\\)\\s *") 
```

I'll write a php-mode test and raise a PR this weekend if you're happy with the fix. In the meanwhile you can solve the problem by adding that configuration to your `php-mode-hook`.

Here's a gif showing the behaviour of Emacs 24.5.1 before and after evaluating the form above:
![php-mode-76](https://cloud.githubusercontent.com/assets/30650/13004201/0007a244-d172-11e5-899e-625c4c1284ef.gif)

**Comment by NateEag** [comment]
@trashofmasters I am not actively using php-mode these days, but thanks for the info. Glad to hear you've found a workaround for this.

**Comment by zonuexe** [comment]
I wasn't aware of this issue, but maybe https://github.com/emacs-php/php-mode/pull/530/files seems to fix this issue. Thanks for reporting!

**Comment by NateEag** [comment]
You're very welcome. Thanks for your years of faithful maintenance, @zonuexe !
