### ISSUE TITLE
emacs master results in error

### ISSUE THREAD

**Issue by hexmode** [emacs-php/php-mode#764]
⛔ Error (use-package): php-mode/:catch: Eager macro-expansion failure: (void-variable flymake-allowed-file-name-masks)

**Comment by claytonrcarter** [comment]
I just ran into this myself, in Doom. At first, I was able to work around by adding `(setq flymake-allowed-file-name-masks '())` to my config before I loaded any php files, but then it looks like it may already be fixed on master via #765. Indeed, evaling `(require 'flymake-proc)` before loading any PHP files also seems to work. I don't know if that's a "proper" fix, or just a coincidence, but it's now working for me. 😄

**Comment by zonuexe** [comment]
@hexmode @claytonrcarter 
Thanks for reporting, the problem has been fixed.
