### ISSUE TITLE
Newline Indentation aligning with equal sign

### ISSUE THREAD

**Issue by jstoks** [emacs-php/php-mode#774]
Having `php-lineup-string-cont` as part of `statement-cont` causes the cursor to align with the equals sign for assignments even when there's no string. There is no interaction with `php-lineup-cascaded-calls` because I have that option disabled.

Actual:
```php
$result = Operation::make()
        ->someFunction();
```

Expected:
```php
$result = Operation::make()
    ->someFunction();
```

(Seems related to #745)

**Comment by zonuexe** [comment]
@jstoks Perhaps merging #777 resolved this issue. This problem seems to have been introduced by some strange change in the past unrelated to the PEAR Coding Standards. Please feel free to send any feedback regarding PEAR style to #776.

Thank you for your report!

**Comment by cweiske** [comment]
This is fixed - thanks!

**Comment by jstoks** [comment]
Thank You!
