### ISSUE TITLE
`php-function-call` face does not inherit from `font-lock-function-call-face`

### ISSUE THREAD

**Issue by bricka** [emacs-php/php-mode#782]
https://www.gnu.org/software/emacs/manual/html_node/elisp/Faces-for-Font-Lock.html#index-font_002dlock_002dfunction_002dcall_002dface

As far as I can tell, this face was added in Emacs 29.1, so it's pretty new :).

In an Emacs version with this face, we get nicer highlighting :).

I'm happy to put up an MR, but I'm not sure how we go about supporting different versions of Emacs. If I just inherit from this, will it "Just Work" in older versions of Emacs? Or do I need to do something special here?

**Comment by zonuexe** [comment]
@bricka Thanks for the suggestion!

Please use the `php-doc-annotation-tag` face, but in older Emacs versions, that face inherits `nil`, so you can use `when` instead of `if`.

**Comment by zonuexe** [comment]
Sorry, this face doesn't have a corresponding variable, so this code doesn't make sense. Instead, check with the following expression:

```elisp
(when (get 'font-lock-function-call-face 'face-defface-spec)
  ...)
```
