### ISSUE TITLE
Highlight of first heredoc with quotes broken depending on how many characters exists before it

### ISSUE THREAD

**Issue by flaviovs** [emacs-php/php-mode#785]
It took me some time to replicate this with a minimal example: when the file below loads, the single quote inside the heredoc is interpreted as an opening string, breaking the highlight from there downwards. Now the strangest things:

* If I remove one single character before the heredoc, the file loads with highlighting working fine.
* If I do any edit anywhere **before** the heredoc -- either adding or removing characters -- then highlighting is fixed.

Can anyone replicate this? Perhaps a _font-lock_ issue?

```php
<?php

//....................

class Test
{
    public function a12345678()
    {
        //........
        //................................................
        //........................
        //.....................................
        //....................................................
        //....
        //
    }

    public function a123456789012345678901()
    {
        // .................

        // ..............
        // ........
        // .

        echo <<<EOTXT
            I'm here.
            EOTXT;
    }

    public function notHighlighted()
    {
    }
}
```

Here's how it looks in my computer:

![image](https://github.com/emacs-php/php-mode/assets/1832699/e4eda580-f6de-4151-8b1f-568782e455fe)

Stock Debian Emacs 28.2, php-mode-20240621.742 from ELPA.

**Comment by zonuexe** [comment]
@flaviovs Thank you for your report!

The number 500 is based on the default value of `syntax-propertize-chunk-size`, which was introduced in #531 to improve performance. Your report was an important clue to the problem with the previous approach.

We are very grateful for your bug report.

**Comment by flaviovs** [comment]
Glad I could help. Thanks for looking into this, @zonuexe.
