### ISSUE TITLE
php-mode has broken auto-complete

### ISSUE THREAD

**Issue by tcuthbert** [emacs-php/php-mode#91]
I have latest auto-complete + latest php-mode via git.
auto-complete works with all my other modes (lisp, python, c/cc-mode).
I can't get completion to work with php-mode.
Not sure what further info you will need so let me know and I will provide.

**Comment by syohex** [comment]
![auto-complete-php](https://cloud.githubusercontent.com/assets/554281/6022457/430234b2-ac00-11e4-8827-a071f052cd2b.gif)

Do you still have this issue ? `TAB` and `RET` looks work well.

```lisp
(require 'auto-complete-config)
(global-auto-complete-mode t)
(ac-config-default)
```
